version: '3.8'

services:
  ddpm-container:  
    build:
      context: .
    volumes:
      - ./data:/diffusion-model/data
      - ./model:/diffusion-model/model
      - ./logs:/diffusion-model/logs
      - ./wandb:/diffusion-model/wandb
      - ./stat.json:/diffusion-model/stat.json